In [1]:
import pandas as pd
import requests

API_KEY = "67ad1bea200726.95055451"
BASE_URL = "https://eodhd.com/api"

## List all supported exchanges

In [2]:
url = f"{BASE_URL}/exchanges-list/?api_token={API_KEY}&fmt=json"
resp = requests.get(url)
df_exchanges = pd.DataFrame(resp.json())
df_exchanges.head()
df_exchanges.to_csv("exchanges_list.csv", index=False)

In [5]:
df_exchanges.head(76)

,Name,Code,OperatingMIC,Country,Currency,CountryISO2,CountryISO3
0,USA Stocks,US,"XNAS, XNYS, OTCM",USA,USD,US,USA
1,London Exchange,LSE,XLON,UK,GBP,GB,GBR
2,NEO Exchange,NEO,NEOE,Canada,CAD,CA,CAN
3,TSX Venture Exchange,V,XTSX,Canada,CAD,CA,CAN
4,Toronto Exchange,TO,XTSE,Canada,CAD,CA,CAN
...,...,...,...,...,...,...,...
71,Government Bonds,GBOND,None,Unknown,Unknown,,
72,Money Market Virtual Exchange,MONEY,None,Unknown,Unknown,,
73,Europe Fund Virtual Exchange,EUFUND,None,Unknown,EUR,,
74,Istanbul Stock Exchange,IS,XIST,Turkey,TRY,TR,TUR
75,Cryptocurrencies,CC,CRYP,Unknown,USD,,

In [6]:
countries = ['India', 'Canada']
df_exchanges[df_exchanges['Country'].isin(countries)]

,Name,Code,OperatingMIC,Country,Currency,CountryISO2,CountryISO3
2,NEO Exchange,NEO,NEOE,Canada,CAD,CA,CAN
3,TSX Venture Exchange,V,XTSX,Canada,CAD,CA,CAN
4,Toronto Exchange,TO,XTSE,Canada,CAD,CA,CAN
51,National Stock Exchange of India,NSE,XNSE,India,INR,IN,IND

## List all tickers on TSX exchange

In [7]:
# List all tickers on TSX
url = f"{BASE_URL}/exchange-symbol-list/TO?api_token={API_KEY}&fmt=json"
resp = requests.get(url)

# Print response status and preview
print("Status Code:", resp.status_code)
print("Preview:\n", resp.text[:300])

# Convert to DataFrame
tickers = resp.json()
df_tickers = pd.DataFrame(tickers)

# Show some sample tickers
print(df_tickers.head())

# Save to CSV
df_tickers.to_csv("tsx_tickers_list.csv", index=False)

Status Code: 200
Preview:
 [{"Code":"0P0000704A","Name":"RBC North American Value Fund A","Country":"Canada","Exchange":"TO","Currency":"CAD","Type":"FUND","Isin":null},{"Code":"0P00007060","Name":"RBC Canadian Money Market Fund A","Country":"Canada","Exchange":"TO","Currency":"CAD","Type":"FUND","Isin":null},{"Code":"0P00007
         Code                                      Name Country Exchange  \
0  0P0000704A           RBC North American Value Fund A  Canada       TO
1  0P00007060          RBC Canadian Money Market Fund A  Canada       TO
2  0P00007061                RBC Canadian Equity Fund A  Canada       TO
3  0P00007065                  RBC mondial d'Ã©nergie A  Canada       TO
4  0P00007069  RBC Portefeuille de croissance sÃ©lect A  Canada       TO

  Currency  Type  Isin
0      CAD  FUND  None
1      CAD  FUND  None
2      CAD  FUND  None
3      CAD  FUND  None
4      CAD  FUND  None

In [8]:
df = pd.read_csv("tsx_tickers_list.csv")

In [9]:
df.head()

,Code,Name,Country,Exchange,Currency,Type,Isin
0,0P0000704A,RBC North American Value Fund A,Canada,TO,CAD,FUND,NaN
1,0P00007060,RBC Canadian Money Market Fund A,Canada,TO,CAD,FUND,NaN
2,0P00007061,RBC Canadian Equity Fund A,Canada,TO,CAD,FUND,NaN
3,0P00007065,RBC mondial d'Ã©nergie A,Canada,TO,CAD,FUND,NaN
4,0P00007069,RBC Portefeuille de croissance sÃ©lect A,Canada,TO,CAD,FUND,NaN

In [10]:
df.shape

(2569, 7)

In [11]:
df['Type'].unique()

array(['FUND', 'Common Stock', 'ETF', 'Preferred Stock', nan],
      dtype=object)

In [12]:
df[df['Type']=='Preferred Stock']

,Code,Name,Country,Exchange,Currency,Type,Isin
153,AIM-PA,Aimia Srs 1 Cum Rte Rst Prf,Canada,TO,CAD,Preferred Stock,CA00900Q2027
154,AIM-PC,Aimia Inc Pref C,Canada,TO,CAD,Preferred Stock,CA00900Q4007
157,ALA-PA,Altagas Cum Red 5 Yr Rate A Prf,Canada,TO,CAD,Preferred Stock,CA0213612090
158,ALA-PB,Altagas Ltd Pref B,Canada,TO,CAD,Preferred Stock,CA0213613080
159,ALA-PG,Altagas Ltd Pref G,Canada,TO,CAD,Preferred Stock,CA0213618865
...,...,...,...,...,...,...,...
2324,XMF-PB,M Split Corp Pref B,Canada,TO,CAD,Preferred Stock,CA55376A5035
2325,XMF-PC,M Split Corp Pref C,Canada,TO,CAD,Preferred Stock,CA55376A8005
2369,XTD-PA,TDb Split Corp Pref A,Canada,TO,CAD,Preferred Stock,CA87234Y1007
2388,YCM-PA,Commerce Split Corp Pref A,Canada,TO,CAD,Preferred Stock,CA2007015068
2389,YCM-PB,Commerce Split Corp Pref B,Canada,TO,CAD,Preferred Stock,CA2007016058

In [13]:
df[df['Type']=='Common Stock']

,Code,Name,Country,Exchange,Currency,Type,Isin
118,AAB,Aberdeen International Inc.,Canada,TO,CAD,Common Stock,CA0030691012
119,AAPL,Apple CDR (CAD Hedged),Canada,TO,CAD,Common Stock,NaN
121,AAUC,Allied Gold Corporation,Canada,TO,CAD,Common Stock,NaN
122,AAV,Advantage Oil & Gas Ltd.,Canada,TO,CAD,Common Stock,CA00791P1071
123,ABRA,AbraSilver Resource Corp.,Canada,TO,CAD,Common Stock,NaN
...,...,...,...,...,...,...,...
2375,XTRA,Xtract One Technologies Inc.,Canada,TO,CAD,Common Stock,NaN
2386,Y,Yellow Pages Limited,Canada,TO,CAD,Common Stock,CA9855721069
2387,YCM,Commerce Split Corp,Canada,TO,CAD,Common Stock,CA2007018039
2390,YGR,Yangarra Resources Ltd,Canada,TO,CAD,Common Stock,CA98474P5013
2391,YRB,Yorbeau Resources Inc,Canada,TO,CAD,Common Stock,CA9861913023

 ## EOD OHLCV for AAPL.US (can get only for last one year)

In [14]:
symbol = "SHOP.TO"  # Format: {ticker}.{exchange_code}
BASE_URL = "https://eodhd.com/api"

url = f"{BASE_URL}/eod/{symbol}?api_token={API_KEY}&fmt=json"
resp = requests.get(url)

# Preview response
print("Status Code:", resp.status_code)
print("Preview:\n", resp.text[:300])

# Convert to DataFrame
data = resp.json()
df = pd.DataFrame(data)
df.to_csv("shopify_tsx_eod.csv", index=False)
df.head()

Status Code: 200
Preview:
 [{"date":"2015-05-21","open":35.03,"high":35.3,"low":30,"close":31.25,"adjusted_close":3.125,"volume":2703000},{"date":"2015-05-22","open":32.03,"high":38.03,"low":32,"close":34.94,"adjusted_close":3.494,"volume":3228000},{"date":"2015-05-25","open":35,"high":37.47,"low":35,"close":37.26,"adjusted_c

         date   open   high    low  close  adjusted_close   volume
0  2015-05-21  35.03  35.30  30.00  31.25           3.125  2703000
1  2015-05-22  32.03  38.03  32.00  34.94           3.494  3228000
2  2015-05-25  35.00  37.47  35.00  37.26           3.726  1178000
3  2015-05-26  36.00  37.69  36.00  36.92           3.692   968000
4  2015-05-27  38.00  38.16  33.63  34.50           3.450  1357000

In [15]:
# Step 1: Convert 'date' column to datetime if not already
df['date'] = pd.to_datetime(df['date'])

# Step 2: Get the earliest date
min_date = df['date'].min()

print("Earliest date:", min_date)

Earliest date: 2015-05-21 00:00:00

In [16]:
# Step 1: Convert 'date' column to datetime if not already
df['date'] = pd.to_datetime(df['date'])

# Step 2: Get the earliest date
max_date = df['date'].max()

print("latest date:", max_date)

latest date: 2025-06-20 00:00:00

## Bulk EOD OHLCV for all US tickers (latest day)

In [11]:
url = f"{BASE_URL}/eod-bulk-last-day/TO?api_token={API_KEY}&fmt=json"

resp = requests.get(url)
print(resp.status_code, resp.headers.get('Content-Type'))
print(resp.text[:300])

data = resp.json()
df = pd.DataFrame(data)
df.to_csv("canada_tsx_eod.csv", index=False)

200 application/json
[{"code":"0P00007149","exchange_short_name":"TO","date":"2025-06-17","open":89.2941,"high":89.2941,"low":89.2941,"close":89.2941,"adjusted_close":89.2941,"volume":0},{"code":"0P0000714D","exchange_short_name":"TO","date":"2025-06-17","open":37.8672,"high":37.8672,"low":37.8672,"close":37.8672,"adjus

In [12]:
df = pd.read_csv("canada_tsx_eod.csv")

In [13]:
df.head()

,code,exchange_short_name,date,open,high,low,close,adjusted_close,volume
0,0P00007149,TO,2025-06-17,89.2941,89.2941,89.2941,89.2941,89.2941,0
1,0P0000714D,TO,2025-06-17,37.8672,37.8672,37.8672,37.8672,37.8672,0
2,0P0000716B,TO,2025-06-17,99.0466,99.0466,99.0466,99.0466,99.0466,0
3,0P00007173,TO,2025-06-17,105.2318,105.2318,105.2318,105.2318,105.2318,0
4,0P00007174,TO,2025-06-17,11.6466,11.6466,11.6466,11.6466,11.6466,0

In [14]:
df.shape

(2261, 9)

## Splits data for AAPL.US

In [13]:
url = f"{BASE_URL}/splits/AAPL.US?api_token={API_KEY}&fmt=json"
resp = requests.get(url)

# Check if the response is valid JSON
try:
    data = resp.json()
    df_splits = pd.DataFrame(data)
    display(df_splits.head())
except ValueError:
    print("Failed to decode JSON")
    print("Status Code:", resp.status_code)
    print("Response Text Preview:\n", resp.text[:500])

Failed to decode JSON
Status Code: 403
Response Text Preview:
 Only EOD data allowed for free users. Please, contact our support team: support@eodhistoricaldata.com

## Dividends data for AAPL.US

In [14]:
url = f"{BASE_URL}/dividends/AAPL.US?api_token={API_KEY}&fmt=json"
resp = requests.get(url)
# Check if the response is valid JSON
try:
    data = resp.json()
    df_dividends = pd.DataFrame(data)
    display(df_dividends.head())
except ValueError:
    print("Failed to decode JSON")
    print("Status Code:", resp.status_code)
    print("Response Text Preview:\n", resp.text[:500])

Failed to decode JSON
Status Code: 404
Response Text Preview:
 <!DOCTYPE html>
<html lang="en">
<head>
    <link rel="canonical" href="https://eodhd.com/api/dividends/AAPL.US">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Historical End-of-Day, Intraday, and Streaming Live Prices API with a Free Trial: The Best Global Software for Fundamental Financial Data and Stock Market Information on Over 120,000 Stocks, ETFs, and Funds Worldwide.">

    <meta

## Exchange trading details (US)

In [15]:
url = f"{BASE_URL}/exchange-details/US?api_token={API_KEY}&fmt=json"
resp = requests.get(url)
try:
    data = resp.json()
    df_details = pd.DataFrame(data)
    display(df_details.head())
except ValueError:
    print("Failed to decode JSON")
    print("Status Code:", resp.status_code)
    print("Response Text Preview:\n", resp.text[:500])

Failed to decode JSON
Status Code: 403
Response Text Preview:
 Only EOD data allowed for free users. Please, contact our support team: support@eodhistoricaldata.com