In [2]:
import pandas as pd
import requests

API_KEY = "67ad1bea200726.95055451"
BASE_URL = "https://eodhd.com/api"

## List all supported exchanges

In [3]:
url = f"{BASE_URL}/exchanges-list/?api_token={API_KEY}&fmt=json"
resp = requests.get(url)
df_exchanges = pd.DataFrame(resp.json())
df_exchanges.head()

,Name,Code,OperatingMIC,Country,Currency,CountryISO2,CountryISO3
0,USA Stocks,US,"XNAS, XNYS, OTCM",USA,USD,US,USA
1,London Exchange,LSE,XLON,UK,GBP,GB,GBR
2,NEO Exchange,NEO,NEOE,Canada,CAD,CA,CAN
3,TSX Venture Exchange,V,XTSX,Canada,CAD,CA,CAN
4,Toronto Exchange,TO,XTSE,Canada,CAD,CA,CAN

## List all tickers on US exchange

In [4]:
exchange_code = "US"
url = f"{BASE_URL}/exchange-symbol-list/{exchange_code}?api_token={API_KEY}&fmt=json"
resp = requests.get(url)
df_tickers = pd.DataFrame(resp.json())
df_tickers.head()

,Code,Name,Country,Exchange,Currency,Type,Isin
0,0P000070L2,RBC $U.S. Money Market Fund A,USA,OTC,USD,FUND,None
1,0P0000A2WI,Fidelity American High Yield Sr B,USA,US,USD,FUND,None
2,0P0000A412,Franklin U.S. Opportunities Fund A,USA,PINK,USD,FUND,None
3,0P0000O6WE,Nh Unique College Investing Plan Fidelity 500 ...,USA,NMFQS,USD,FUND,None
4,0P0000O753,Oh Collegeadvantage 529 Vanguard Wellington Op...,USA,NMFQS,USD,FUND,None

 ## EOD OHLCV for AAPL.US (can get only for last one year)

In [6]:
symbol = "AAPL.US"
url = f"{BASE_URL}/eod/{symbol}?api_token={API_KEY}&from=2025-01-01&to=2025-01-10&fmt=json"
resp = requests.get(url)
df_eod = pd.DataFrame(resp.json())
df_eod.head()

         date    open    high     low   close  adjusted_close    volume
0  2025-01-02  248.93  249.10  241.82  243.85        243.2632  55740700
1  2025-01-03  243.36  244.18  241.89  243.36        242.7744  40244100
2  2025-01-06  244.31  247.33  243.20  245.00        244.4104  45045600
3  2025-01-07  242.98  245.55  241.35  242.21        241.6271  40856000
4  2025-01-08  241.92  243.71  240.05  242.70        242.1160  37628900

## Bulk EOD OHLCV for all US tickers (latest day)

In [11]:
url = f"{BASE_URL}/eod-bulk-last-day/US?api_token={API_KEY}&fmt=json"
resp = requests.get(url)

# Check if the response is valid JSON
try:
    data = resp.json()
    df_bulk_eod = pd.DataFrame(data)
    display(df_bulk_eod.head())
except ValueError:
    print("Failed to decode JSON")
    print("Status Code:", resp.status_code)
    print("Response Text Preview:\n", resp.text[:500])

Failed to decode JSON
Status Code: 423
Response Text Preview:
 Bulk requests are prohibited for free users. Please, contact our support team: support@eodhistoricaldata.com

## Splits data for AAPL.US

In [13]:
url = f"{BASE_URL}/splits/AAPL.US?api_token={API_KEY}&fmt=json"
resp = requests.get(url)

# Check if the response is valid JSON
try:
    data = resp.json()
    df_splits = pd.DataFrame(data)
    display(df_splits.head())
except ValueError:
    print("Failed to decode JSON")
    print("Status Code:", resp.status_code)
    print("Response Text Preview:\n", resp.text[:500])

Failed to decode JSON
Status Code: 403
Response Text Preview:
 Only EOD data allowed for free users. Please, contact our support team: support@eodhistoricaldata.com

## Dividends data for AAPL.US

In [14]:
url = f"{BASE_URL}/dividends/AAPL.US?api_token={API_KEY}&fmt=json"
resp = requests.get(url)
# Check if the response is valid JSON
try:
    data = resp.json()
    df_dividends = pd.DataFrame(data)
    display(df_dividends.head())
except ValueError:
    print("Failed to decode JSON")
    print("Status Code:", resp.status_code)
    print("Response Text Preview:\n", resp.text[:500])

Failed to decode JSON
Status Code: 404
Response Text Preview:
 <!DOCTYPE html>
<html lang="en">
<head>
    <link rel="canonical" href="https://eodhd.com/api/dividends/AAPL.US">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Historical End-of-Day, Intraday, and Streaming Live Prices API with a Free Trial: The Best Global Software for Fundamental Financial Data and Stock Market Information on Over 120,000 Stocks, ETFs, and Funds Worldwide.">

    <meta

## Exchange trading details (US)

In [15]:
url = f"{BASE_URL}/exchange-details/US?api_token={API_KEY}&fmt=json"
resp = requests.get(url)
try:
    data = resp.json()
    df_details = pd.DataFrame(data)
    display(df_details.head())
except ValueError:
    print("Failed to decode JSON")
    print("Status Code:", resp.status_code)
    print("Response Text Preview:\n", resp.text[:500])

Failed to decode JSON
Status Code: 403
Response Text Preview:
 Only EOD data allowed for free users. Please, contact our support team: support@eodhistoricaldata.com